# =============================
# = Spring
# =============================
spring:
  datasource:
    url: jdbc:mysql://realmeet-db-tadeu.cfe5ogqriu0y.sa-east-1.rds.amazonaws.com:3306/realmeet?severTimezone=UTC&useSSL=false
    username: root