# =============================
# = Spring
# =============================
spring:
  datasource:
    url: jdbc:mysql://realmeet-aws.cfe5ogqriu0y.sa-east-1.rds.amazonaws.com:3306/realmeet-aws?severTimezone=UTC&useSSL=false
    username: admin